# Generated by Django 5.2.8 on 2025-11-09 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_vehiculo_email_camionero_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='tipo',
            field=models.CharField(choices=[('Factura', 'Factura'), ('Devolucion', 'Devolución')], max_length=20),
        ),
    ]
