# Generated by Django 5.2.8 on 2025-11-13 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_documento_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='nombre_empresa',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='rut',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
